src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\User;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $adult_tickets;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $child_tickets;

    /**
     * @ORM\Column(type="datetime")
     */
    private $reservation_date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdultTickets(): ?int
    {
        return $this->adult_tickets;
    }

    public function setAdultTickets(int $adult_tickets): self
    {
        $this->adult_tickets = $adult_tickets;

        return $this;
    }

    public function getChildTickets(): ?int
    {
        return $this->child_tickets;
    }

    public function setChildTickets(?int $child_tickets): self
    {
        $this->child_tickets = $child_tickets;

        return $this;
    }

    public function getReservationDate(): ?\DateTimeInterface
    {
        return $this->reservation_date;
    }

    public function setReservationDate(\DateTimeInterface $reservation_date): self
    {
        $this->reservation_date = $reservation_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ReservationType extends AbstractType
{

    // private $security;

    // public function __construct(Security $security)
    // {
    //     $this->security = $security;
    // }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // $currentUser = $this->security->getUser();
        $builder
            // ->add(
            //     'user',
            //     TextType::class,
            //     [
            //         'class' => User::class,
            //         'label' => 'Utilisateur',
            //         'choice_label' => 'username',
            //         'data' => $currentUser->getUsername(),
            //         'attr' =>[
            //         'disabled' => true,
            //         ],
            //     ]
            // )
            ->add(
                'adult_tickets',
                TextType::class,
                [
                    "label" => "Billets adulte"
                ]
            )
            ->add(
                'child_tickets',
                TextType::class,
                [
                    "label" => "Billets enfant"
                ]
            )
            ->add(
                'reservation_date',
                null,
                [
                    "label" => "Date de réservation"
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/reservation")
 */
class ReservationController extends AbstractController
{
    /**
     * @Route("/", name="reservation_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository, UserInterface $user=null): Response
    {
        $reservations = $this->getDoctrine()->getManager()
                        ->getRepository(Reservation::class)->findBy(['user' => $user]);
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservations,
        ]);
    }

    /**
     * @Route("/new", name="reservation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservation->setUser($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);
        // dd($this->getUser());
        if ($form->isSubmitted() && $form->isValid()) {
            // dd($this->getUser());
            $reservation->setUser($this->getUser());
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Reservation $reservation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index');
    }
}

templates/reservation/_delete_form.html.twig
{# <script> function swa() { return confirm("are you sure");}
</script> #}

<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Etes-vous sûr?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn btn-danger mt-5">Supprimer</button>
</form>

templates/reservation/_form.html.twig
<div class="containerBoxes rounded my-5">
    <div class="p-5">
        {# {{ form_row(form.reservation_date) }} #}
        
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {# si on est sur la route de modification #}
        {% if app.request.get('_route') == 'reservation_edit' %}
            <div class="row">
                <div class="col-lg-6 col-xs-12 mb-3">
                    <button class="btn btn-success">{{ button_label }}</button>
                </div>
                <div class="col-lg-6 col-xs-12">
                </div>
            </div>
        {% else %}
        <button class="btn btn-success">{{ button_label|default('Réserver') }}</button>
        {% endif %}
        {{ form_end(form) }}
        <a href="{{ path('reservation_index') }}" class="btn btn-dark my-5">Retour à la liste</a>        
    </div>
</div>

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la réservation{% endblock %}

{% block body %}
    {{ include('reservation/_delete_form.html.twig') }}
    {{ include('reservation/_form.html.twig', {'button_label': 'Enregistrer les modifications'}) }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block body %}

    {% if app.user == "" %}
        <div class="d-flex containerBoxes rounded p-5 row my-5 flex-column text-center align-items-center">
            <p>Dépêchez vous de vous connecter avant de rater vos futurs rendez-vous chez nous.
                <br>Ne laissez pas tomber ce beau monde qui vous a tant apporté...</p>
            <a class="btn btn-dark mt-5" href="{{ path('app_login') }}">Sauver le monde!</a>
        </div>
    {% else %}
        <div class="d-flex containerBoxes rounded p-5 row my-5 flex-direction-column text-center">
            <h3>Vos réservations</h3>
            <table class="table">
                <tbody>
                {% for reservation in reservations %}
                    <tr>
                        <td  class="text-white">Le {{ reservation.reservationDate ? reservation.reservationDate|date('d/m/y') : '' }}</td>
                        <td>
                            <a href="{{ path('reservation_show', {'id': reservation.id}) }}" class="btn btn-dark">Voir</a>
                            <a href="{{ path('reservation_edit', {'id': reservation.id}) }}" class="btn btn-warning">Modifier</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5" class="text-white">Vous n'avez pas encore de réservation, dépêchez vous!</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <a href="{{ path('reservation_new') }}" class="btn btn-warning">Nouvelle réservation</a>
        </div>
    {% endif %}

{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    {{ include('reservation/_form.html.twig') }}
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <div class="containerBoxes mt-5 rounded">
        <div class="m-5 pt-2">
            <h3 class="my-5">Votre réservation du {{ reservation.reservationDate ? reservation.reservationDate|date('d/m/y') : '' }}</h3>

            <table class="table">
                <tbody>
                    <tr>
                        <th></th>
                        <th>Nombre</th>
                        <th>Prix total</th>
                        <th>(Prix unitaire)</th>
                    </tr>
                    <tr>
                        <th>Billets adulte</th>
                        <td>{{ reservation.adultTickets }}</td>
                        <td>{{ reservation.adultTickets * 15 }}</td>
                        <td>15€</td>
                    </tr>
                    <tr>
                        <th>Billets enfant</th>
                        <td>{{ reservation.childTickets }}</td>
                        <td>{{ reservation.childTickets * 7 }}</td>
                        <td>7€</td>
                    </tr>
                    <tr>
                        
                        <th>Total</th>
                        <td>{{ reservation.adultTickets + reservation.childTickets}}</td>
                        <td>{{ reservation.adultTickets * 15 + reservation.childTickets * 7 }} €</td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
            <div class="row">
                <div class="col-lg-6 col-xs-12 mb-3">
                    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}" class="btn btn-warning">Modifier</a>
                </div>
                <div class="col-lg-6 col-xs-12">
                    {{ include('reservation/_delete_form.html.twig') }}
                </div>
            </div>
            <a href="{{ path('reservation_index') }}" class="btn btn-dark mr-5 my-5">Retour à la liste</a>
        </div>
        
    </div>
{% endblock %}